version: '3.5'

services:
  ubuntu:
    build:
      context: .
    image: p4f
    container_name: p4f
    tty: true
    volumes:
      - ./histograms:/Prophecy4f-3.0/HISTOGRAMS
      - ./histunweighted:/Prophecy4f-3.0/HISTUNWEIGHTED
      - ./unweightedevents:/Prophecy4f-3.0/UNWEIGHTEDEVENTS
      - ./inputdir:/Prophecy4f-3.0/inputdir
